stages:
  - update-images
  - build

.template: &prepare-build-image
  stage: update-images
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:latest $BUILD_CONTEXT_DIR
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest

.template: &ctc
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - cmake --build . --target test
    - gcovr -r ..


update-fedora30-image:
  <<: *prepare-build-image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/fedora-30-$CI_COMMIT_REF_NAME
    BUILD_CONTEXT_DIR: images/fedora30

update-archlinux-image:
  <<: *prepare-build-image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/archlinux-$CI_COMMIT_REF_NAME
    BUILD_CONTEXT_DIR: images/archlinux

update-ubuntu-image:
  <<: *prepare-build-image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu-19.04-$CI_COMMIT_REF_NAME
    BUILD_CONTEXT_DIR: images/ubuntu-19.04

update-tumbleweed-image:
  <<: *prepare-build-image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/opensuse-tumbleweed-$CI_COMMIT_REF_NAME
    BUILD_CONTEXT_DIR: images/opensuse/tumbleweed

build-fedora30:
  <<: *ctc
  image: $CI_REGISTRY_IMAGE/fedora-30-$CI_COMMIT_REF_NAME

build-ubuntu-19.04:
  <<: *ctc
  image: $CI_REGISTRY_IMAGE/ubuntu-19.04-$CI_COMMIT_REF_NAME

build-openususe-tumbleweed:
  <<: *ctc
  image: $CI_REGISTRY_IMAGE/opensuse-tumbleweed-$CI_COMMIT_REF_NAME

build-archlinux:
  <<: *ctc
  image: $CI_REGISTRY_IMAGE/archlinux-$CI_COMMIT_REF_NAME
