sudo: required
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - curl
    - cmake

script: 
  - sudo pip install conan
  - mkdir ~/llvm
  - cd ~/llvm
  - curl "http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz" -o "llvm.tar.xz"
  - tar xvf llvm.tar.xz --strip 1 # keep the v. makes debugging builds easier

  - cd ..
  - export Clang_DIR=./llvm/lib/cmake/clang

  - mkdir build
  - cd build
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake ..
  - make


