sudo: required
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - curl
    - cmake
    # - python3-pip

script: 
  # - pip3 install conan pip3 install fails and it seems to be a bug in pip. luckily we have python2 pip to fall back to
  - pip install conen
  - mkdir ~/llvm
  - cd ~/llvm
  - curl "http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz" -o "llvm.tar.xz"
  - tar xf llvm.tar.xz --strip 1

  - cd ..
  - export Clang_DIR=./llvm/lib/cmake/clang

  - cd build
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake $TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Release
  - make


