language: cpp
script: cmake
compiler: 
  - clang
  - gcc
before_install:
  - sudo apt-get install -y gcc7 pip
  - sudo pip install conan
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make


