sudo: false
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - curl
    - cmake
    - lcov
    # - python3-pip

script: 
  # - pip3 install conan pip3 install fails and it seems to be a bug in pip. luckily we have python2 pip to fall back to
  # - sudo pip install --upgrade pip
  - sudo -H pip install conan
  - mkdir ~/llvm
  - cd ~/llvm
  - curl "http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz" -o "llvm.tar.xz"
  - tar xf llvm.tar.xz --strip 1

  - cd ..
  - export Clang_DIR=~/llvm/lib/cmake/clang

  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_CONAN_DEPENDENCIES=all ..
  - cmake --build .
  - ctest
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

